# Generated by Django 5.0.6 on 2024-08-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='language',
        ),
    ]
